
package com.thirdeye.backend.testgen;

import com.thirdeye.backend.entity.Finding;

import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Deterministic JUnit test generator for ThirdEye static-analysis findings.
 *
 * SQLI-001 and CRED-001 generate regression tests against the actual
 * ThirdEye analysis rules. Other rules retain an explicit scaffold.
 *
 * Generated tests are NOT executed by this class.
 */
public final class TestCodeGenerator {

    private static final Pattern RULE_ID_PATTERN =
            Pattern.compile("\\[([A-Z]+-\\d{3})\\]");

    private TestCodeGenerator() {
    }

    public static String generate(Finding finding) {
        String ruleId = extractRuleId(finding.getDescription());

        return switch (ruleId) {
            case "SQLI-001" -> generateSqlInjectionTest(finding);
            case "CRED-001" -> generateCredentialTest(finding);
            default -> generateScaffold(finding, ruleId);
        };
    }

    public static String testType(Finding finding) {
        return extractRuleId(finding.getDescription());
    }

    public static String testFilePath(Finding finding) {
        String file = finding.getFile();

        if (file == null || file.isBlank()) {
            file = "Unknown.java";
        }

        file = file.replace('\\', '/');
        int slash = file.lastIndexOf('/');

        if (slash >= 0) {
            file = file.substring(slash + 1);
        }

        if (file.endsWith(".java")) {
            file = file.substring(0, file.length() - 5);
        }

        String rule = testType(finding)
                .replace("-", "_")
                .toLowerCase(Locale.ROOT);

        return "src/test/java/" + safeClassName(file)
                + "_" + rule
                + "_finding" + finding.getId()
                + "_Test.java";
    }

    private static String generateSqlInjectionTest(Finding finding) {
        String className = safeClassName(
                baseName(finding.getFile()))
                + "SqlInjectionFinding"
                + finding.getId()
                + "Test";

        String file = stringOrDefault(
                finding.getFile(), "unknown");

        int line = finding.getLine();

        String vulnerableCode =
                "String query = \"SELECT * FROM users WHERE name='"
                        + "\" + username + \"'\";";

        StringBuilder out = new StringBuilder();

        out.append("""
                // GENERATED BY ThirdEye
                // Rule: SQLI-001 | Finding #%d
                // Tests the actual ThirdEye SQL injection detection rule.
                // These tests have NOT been executed by the generator.

                import com.thirdeye.backend.analysis.DiffLine;
                import com.thirdeye.backend.analysis.RuleFinding;
                import com.thirdeye.backend.analysis.rules.SqlInjectionRule;
                import org.junit.jupiter.api.DisplayName;
                import org.junit.jupiter.api.Test;

                import java.util.List;

                import static org.junit.jupiter.api.Assertions.*;

                class %s {

                    private final SqlInjectionRule rule =
                            new SqlInjectionRule();

                    @Test
                    @DisplayName("Detect SQL query concatenation")
                    void detectsSqlConcatenation() {
                        DiffLine vulnerableLine = new DiffLine(
                                %s,
                                %d,
                                %s
                        );

                        List<RuleFinding> findings =
                                rule.analyze(List.of(vulnerableLine));

                        assertEquals(1, findings.size());

                        RuleFinding result = findings.get(0);

                        assertEquals("SQLI-001", result.getRuleId());
                        assertEquals(%s, result.getFile());
                        assertEquals(%d, result.getLine());
                        assertEquals("security", result.getCategory());
                        assertEquals("high", result.getSeverity());
                    }

                    @Test
                    @DisplayName("Do not flag parameterized SQL")
                    void doesNotFlagParameterizedQuery() {
                        DiffLine safeLine = new DiffLine(
                                "UserService.java",
                                10,
                                "String query = \\"SELECT * FROM users WHERE name = ?\\";"
                        );

                        List<RuleFinding> findings =
                                rule.analyze(List.of(safeLine));

                        assertTrue(findings.isEmpty());
                    }

                    @Test
                    @DisplayName("Do not flag ordinary string concatenation")
                    void doesNotFlagNonSqlConcatenation() {
                        DiffLine safeLine = new DiffLine(
                                "UserService.java",
                                11,
                                "String message = \\"Hello \\" + username;"
                        );

                        List<RuleFinding> findings =
                                rule.analyze(List.of(safeLine));

                        assertTrue(findings.isEmpty());
                    }

                    @Test
                    @DisplayName("Detect SQL concatenation with unsafe execution")
                    void detectsUnsafeExecutionAsCritical() {
                        DiffLine vulnerableLine = new DiffLine(
                                "UserService.java",
                                12,
                                "String query = \\"SELECT * FROM users WHERE name='\\" + username + \\"'\\"; Statement stmt; stmt.executeQuery(query);"
                        );

                        List<RuleFinding> findings =
                                rule.analyze(List.of(vulnerableLine));

                        assertEquals(1, findings.size());
                        assertEquals("critical",
                                findings.get(0).getSeverity());
                    }
                }
                """.formatted(
                finding.getId(),
                className,
                javaString(file),
                line,
                javaString(vulnerableCode),
                javaString(file),
                line
        ));

        return out.toString();
    }

    private static String generateCredentialTest(Finding finding) {
        String className = safeClassName(
                baseName(finding.getFile()))
                + "CredentialFinding"
                + finding.getId()
                + "Test";

        String file = stringOrDefault(
                finding.getFile(), "unknown");

        int line = finding.getLine();

        StringBuilder out = new StringBuilder();

        out.append("""
                // GENERATED BY ThirdEye
                // Rule: CRED-001 | Finding #%d
                // Tests the actual ThirdEye hardcoded credential rule.
                // These tests have NOT been executed by the generator.

                import com.thirdeye.backend.analysis.DiffLine;
                import com.thirdeye.backend.analysis.RuleFinding;
                import com.thirdeye.backend.analysis.rules.HardcodedCredentialRule;
                import org.junit.jupiter.api.DisplayName;
                import org.junit.jupiter.api.Test;

                import java.util.List;

                import static org.junit.jupiter.api.Assertions.*;

                class %s {

                    private final HardcodedCredentialRule rule =
                            new HardcodedCredentialRule();

                    @Test
                    @DisplayName("Detect hardcoded password")
                    void detectsHardcodedPassword() {
                        DiffLine vulnerableLine = new DiffLine(
                                %s,
                                %d,
                                "String password = \\"mysecret\\";"
                        );

                        List<RuleFinding> findings =
                                rule.analyze(List.of(vulnerableLine));

                        assertEquals(1, findings.size());

                        RuleFinding result = findings.get(0);

                        assertEquals("CRED-001", result.getRuleId());
                        assertEquals(%s, result.getFile());
                        assertEquals(%d, result.getLine());
                        assertEquals("critical", result.getSeverity());
                        assertEquals("security", result.getCategory());
                    }

                    @Test
                    @DisplayName("Ignore environment variable lookup")
                    void doesNotFlagEnvironmentVariable() {
                        DiffLine safeLine = new DiffLine(
                                "UserService.java",
                                10,
                                "String password = System.getenv(\\"APP_PASSWORD\\");"
                        );

                        List<RuleFinding> findings =
                                rule.analyze(List.of(safeLine));

                        assertTrue(findings.isEmpty());
                    }

                    @Test
                    @DisplayName("Ignore placeholder credentials")
                    void doesNotFlagPlaceholder() {
                        DiffLine safeLine = new DiffLine(
                                "UserService.java",
                                11,
                                "String password = \\"changeme\\";"
                        );

                        List<RuleFinding> findings =
                                rule.analyze(List.of(safeLine));

                        assertTrue(findings.isEmpty());
                    }

                    @Test
                    @DisplayName("Downgrade credential findings in test files")
                    void downgradesTestFileFinding() {
                        DiffLine testLine = new DiffLine(
                                "UserServiceTest.java",
                                12,
                                "String password = \\"mysecret\\";"
                        );

                        List<RuleFinding> findings =
                                rule.analyze(List.of(testLine));

                        assertEquals(1, findings.size());
                        assertEquals("low",
                                findings.get(0).getSeverity());
                    }
                }
                """.formatted(
                finding.getId(),
                className,
                javaString(file),
                line,
                javaString(file),
                line
        ));

        return out.toString();
    }

    /**
     * Explicit fallback for rules without implemented test templates.
     */
    private static String generateScaffold(
            Finding finding, String ruleId) {

        String className = safeClassName(
                baseName(finding.getFile()))
                + "GeneratedFinding"
                + finding.getId()
                + "Test";

        return """
                // GENERATED BY ThirdEye
                // Rule: %s | Finding #%d
                // Status: NOT_RUN
                //
                // SCAFFOLD: No executable test template is implemented
                // for this rule yet. This is not a verified regression test.

                import org.junit.jupiter.api.Test;
                import static org.junit.jupiter.api.Assertions.fail;

                class %s {

                    @Test
                    void testRequiresImplementation() {
                        fail("Test scaffold: implement and review the test "
                                + "before execution.");
                    }
                }
                """.formatted(
                ruleId,
                finding.getId(),
                className
        );
    }

    private static String extractRuleId(String description) {
        if (description == null || description.isBlank()) {
            return "UNKNOWN";
        }

        Matcher matcher = RULE_ID_PATTERN.matcher(description);

        if (matcher.find()) {
            return matcher.group(1);
        }

        return "UNKNOWN";
    }

    private static String baseName(String file) {
        if (file == null || file.isBlank()) {
            return "Unknown";
        }

        String normalized = file.replace('\\', '/');
        int slash = normalized.lastIndexOf('/');

        if (slash >= 0) {
            normalized = normalized.substring(slash + 1);
        }

        if (normalized.endsWith(".java")) {
            normalized = normalized.substring(
                    0, normalized.length() - 5);
        }

        return normalized;
    }

    private static String safeClassName(String value) {
        if (value == null || value.isBlank()) {
            return "Unknown";
        }

        String cleaned = value.replaceAll("[^A-Za-z0-9_$]", "_");

        if (cleaned.isBlank()
                || !Character.isJavaIdentifierStart(cleaned.charAt(0))) {
            cleaned = "Generated_" + cleaned;
        }

        return cleaned;
    }

    private static String stringOrDefault(
            String value, String fallback) {

        return value == null || value.isBlank()
                ? fallback : value;
    }

    /**
     * Escapes a value as a Java string literal, including its quotes.
     * Used to safely embed source values in generated Java tests.
     */
    private static String javaString(String value) {
        if (value == null) {
            return "null";
        }

        StringBuilder escaped = new StringBuilder("\"");

        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);

            switch (c) {
                case '\\' -> escaped.append("\\\\");
                case '"' -> escaped.append("\\\"");
                case '\n' -> escaped.append("\\n");
                case '\r' -> escaped.append("\\r");
                case '\t' -> escaped.append("\\t");
                default -> escaped.append(c);
            }
        }

        escaped.append('"');
        return escaped.toString();
    }
}