// GENERATED BY ThirdEye
// Rule: SQLI-001 | Finding #34
// Tests the actual ThirdEye SQL injection detection rule.
// These tests have NOT been executed by the generator.

import com.thirdeye.backend.analysis.DiffLine;
import com.thirdeye.backend.analysis.RuleFinding;
import com.thirdeye.backend.analysis.rules.SqlInjectionRule;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class UserServiceSqlInjectionFinding34Test {

    private final SqlInjectionRule rule =
            new SqlInjectionRule();

    @Test
    @DisplayName("Detect SQL query concatenation")
    void detectsSqlConcatenation() {
        DiffLine vulnerableLine = new DiffLine(
                "UserService.java",
                2,
                "String query = \"SELECT * FROM users WHERE name='\" + username + \"'\";"
        );

        List<RuleFinding> findings =
                rule.analyze(List.of(vulnerableLine));

        assertEquals(1, findings.size());

        RuleFinding result = findings.get(0);

        assertEquals("SQLI-001", result.getRuleId());
        assertEquals("UserService.java", result.getFile());
        assertEquals(2, result.getLine());
        assertEquals("security", result.getCategory());
        assertEquals("high", result.getSeverity());
    }

    @Test
    @DisplayName("Do not flag parameterized SQL")
    void doesNotFlagParameterizedQuery() {
        DiffLine safeLine = new DiffLine(
                "UserService.java",
                10,
                "String query = \"SELECT * FROM users WHERE name = ?\";"
        );

        List<RuleFinding> findings =
                rule.analyze(List.of(safeLine));

        assertTrue(findings.isEmpty());
    }

    @Test
    @DisplayName("Do not flag ordinary string concatenation")
    void doesNotFlagNonSqlConcatenation() {
        DiffLine safeLine = new DiffLine(
                "UserService.java",
                11,
                "String message = \"Hello \" + username;"
        );

        List<RuleFinding> findings =
                rule.analyze(List.of(safeLine));

        assertTrue(findings.isEmpty());
    }

    @Test
    @DisplayName("Detect SQL concatenation with unsafe execution")
    void detectsUnsafeExecutionAsCritical() {
        DiffLine vulnerableLine = new DiffLine(
                "UserService.java",
                12,
                "String query = \"SELECT * FROM users WHERE name='\" + username + \"'\"; Statement stmt; stmt.executeQuery(query);"
        );

        List<RuleFinding> findings =
                rule.analyze(List.of(vulnerableLine));

        assertEquals(1, findings.size());
        assertEquals("critical",
                findings.get(0).getSeverity());
    }
}